
export const SHEET_TABS = {
  TASKS: 'Tasks',
  TASKS_ARCHIVE: 'Tasks_Archive',
  TASK_EVENTS: 'Task_Events',
  PROBLEMS: 'Problems',
  PROBLEM_EVENTS: 'Problem_Events',
  COA: 'CoA',
  FLOW_EVENTS: 'FlowEvents',
  FLOW_EVENTS_ARCHIVE: 'FlowEvents_Archive',
  ADJUSTMENTS_LOG: 'Adjustments_Log',
  BACKPRESSURE_ITEMS: 'BackpressureItems',
  DELTAS: 'Deltas',
  SCORE_RULES: 'Score_Rules',
  SCORES_DAILY: 'Scores_Daily',
  SCORES_WEEKLY: 'Scores_Weekly',
  STREAKS: 'Streaks',
  ROLLUPS_DAILY: 'Rollups_Daily',
  ROLLUPS_WEEKLY: 'Rollups_Weekly',
  REPORT_CARDS: 'Report_Cards',
  STORY_TEMPLATES: 'Story_Templates',
  STORY_INSTANCES: 'Story_Instances',
  COMIC_JOBS: 'Comic_Jobs',
  COMIC_ASSETS_INDEX: 'Comic_Assets_Index',
  COMIC_PANELS: 'Comic_Panels',
  GAME_STATE: 'Game_State',
  WALLET: 'Wallet',
  STORE_ITEMS: 'Store_Items',
  PURCHASES: 'Purchases',
  PROVIDERS: 'Providers',
  PROVIDER_AUDIT: 'Provider_Audit',
  CONFIG_VERSIONS: 'Config_Versions',
  SCHEMA_VERSIONS: 'Schema_Versions',
  ACCESS_POLICY: 'Access_Policy',
};

export const SHEET_HEADERS = {
  [SHEET_TABS.TASKS]: ['id', 'title', 'status', 'focus', 'subfocus', 'weight', 'due_date', 'created_at', 'updated_at', 'parent_id', 'tags'],
  [SHEET_TABS.TASKS_ARCHIVE]: ['id', 'title', 'status', 'focus', 'subfocus', 'weight', 'due_date', 'created_at', 'updated_at', 'parent_id', 'tags', 'archived_at'],
  [SHEET_TABS.TASK_EVENTS]: ['id', 'task_id', 'event_type', 'old_value', 'new_value', 'timestamp', 'user_id'],
  [SHEET_TABS.PROBLEMS]: ['id', 'title', 'status', 'hypothesis', 'rca', 'created_at', 'updated_at'],
  [SHEET_TABS.PROBLEM_EVENTS]: ['id', 'problem_id', 'event_type', 'details', 'timestamp'],
  [SHEET_TABS.COA]: ['code', 'name', 'type', 'focus', 'subfocus', 'description'],
  [SHEET_TABS.FLOW_EVENTS]: ['id', 'timestamp', 'account_code', 'amount', 'unit', 'description', 'segments_json'],
  [SHEET_TABS.SCORES_DAILY]: ['date', 'sps', 'aps', 'bps', 'metrics_json'],
  [SHEET_TABS.STORY_INSTANCES]: ['id', 'date', 'narrative', 'type', 'model_used'],
  [SHEET_TABS.PROVIDERS]: ['id', 'name', 'type', 'api_key_ref', 'config_json', 'status'],
};
